### ISSUE TITLE
Handle deletion/renaming of files

### ISSUE THREAD

**Issue by cknitt** [rolandpeelen/rewatch#47]
I found that rewatch doesn't seem to handle deletion/renaming of files correctly yet.

If I delete a .res together with its .resi, no error is reported even though the module is referenced elsewhere. I just get
 
```
[1/7] ️✅  Built package tree in 0.04s
[2/7] ️✅  Found source files in 0.01s
[3/7] ️✅  Cleaned 2/1391 0.05s
[4/7] ️✅  Parsed 0 source files in 0.02s

[5/7] ️✅  Collected deps in 0.01s
[6/7] ️✅  Compiled 0 modules in 0.00s
[7/7] ️✅  Finished Compilation in 0.13s
```

If I delete a .res file, but leave the .resi, I get

```
thread '<unnamed>' panicked at 'Could not get basename', src/helpers.rs:100:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

**Comment by jfrolich** [comment]
We had some regressions that slipped in with some recent refactorings. I fixed it (see #49) and it and created some tests. It should be fixed in the latest master.

**Comment by cknitt** [comment]
@jfrolich Thanks! I retested with 0.0.12-a67d91d. I can confirm that deleting a .res file, but leaving the corresponding .resi, does not cause a crash anymore. Instead a warning is logged. 👍

However, it is still the case that deleting or renaming modules that are still used elsewhere does not give an error.

**Comment by cknitt** [comment]
Sorry, I mean I retested with 0.0.12-c5ae426 (lastest master), and deleting or renaming modules that are still used elsewhere still did not give me an error.
