### ISSUE TITLE
Suggestion: To have . as a project path by default and make it configurable via flag

### ISSUE THREAD

**Issue by DZakh** [rolandpeelen/rewatch#75]
So we can run `rewatch watch` and, if needed, `rewatch watch --project-path=./apps/demo`

**Comment by DZakh** [comment]
I'm talking about not needing to set `.` and have it by default.

**Comment by rolandpeelen** [comment]
You can do that too, the `.` is implicit :)

**Comment by DZakh** [comment]
I see. Good :)
