### ISSUE TITLE
VSCode plugin does not stay up to date with errors

### ISSUE THREAD

**Issue by TomiS** [rolandpeelen/rewatch#77]
Sorry I cannot be any more specific, but the main problem seems to be that while the build works quite nicely, the VSCode plugin does not seem to receive any changes from the rewatch build system. So errors do not show up, etc.

I am not running the internal build provided by the vscode plugin nor am I running any other external builds (such as the one provided by the vite rescript plugin) as I'm under assumption these should not be necessary or preferred.

Are there any specific configurations or things I should know?

I run rewatch through yarn 1.22 on Ubuntu 22.04

ps. Nice job with the rewatch. After struggling a lot with a couple of new monorepo setups during last few weeks I find this project no less than absolutely critical to the success of ReScript.

**Comment by TomiS** [comment]
Oh, wait, I just realized it doesn't even see any changes in files. Even if I edit and save a `res` file, `rewatch` just goes through all steps without noticing any changes in files like this:
```
[1/7] ️✅  Built package tree in 0.00s
[2/7] ️✅  Found source files in 0.01s
[3/7] ️✅  Cleaned 0/45 0.00s
[4/7] ️✅  Parsed 0 source files in 0.00s
[5/7] ️✅  Collected deps in 0.00s
[6/7] ️✅  Compiled 0 modules in 0.00s
[7/7] ️✅  Finished Compilation in 0.03s
```

**Comment by rolandpeelen** [comment]
@TomiS - Interesting. Can you share a [tree](https://mama.indstate.edu/users/ice/tree/) of your directory structure from the point of where you're running Rewatch? Feel free to redact, but just so we have a rough idea what we're looking at?

Or - what would possibly be even better - a small repo that shows the issue for you?

**Comment by TomiS** [comment]
Ok, after another afternoon of tweaking, I found out it was a stupid user error, like it almost always is. It appears if somebody (me), for some reason (I don't remember) puts something like this into the root package.json
```
  "dependencies": {
    "@child-a": "file:./packages/child-a",
    "@child-b": "file:./packages/child-b"
  },
```
After running `yarn install`, ReScript compiler completely stops generating Js files. I don't know why, maybe it causes some sort of dependency loop or something. But after removing those everything started working, so I can close this. Thanks and sorry.
