### ISSUE TITLE
Support freely configurable suffix for generated .js files

### ISSUE THREAD

**Issue by cknitt** [rolandpeelen/rewatch#78]
Since ReScript 11.0.0-rc.6, the suffix for the generated js files is freely configurable (see https://github.com/rescript-lang/rescript-compiler/pull/6472).

(Well, almost freely, see https://github.com/rescript-lang/rescript-compiler/blob/adb55d016252174237adb5689568ce88032ca2b9/jscomp/bsb/bsb_package_specs.ml#L58.)

**Comment by cknitt** [comment]
Given that create-rescript-app and the official installation instructions for v11 are now using .res.(m)js, it would be great to have this fixed.

**Comment by rolandpeelen** [comment]
Merged in #86
